This produces compile break with: /p/project/cjiff40/kipp1/STB/src/units.f90:52:67:
   52 |          call CFG_get(cfg, "units%" // trim(field_name), unit_name)
      |                                                                   1
Error: There is no specific subroutine for the generic 'cfg_get' at (1)

Revert "give intent in to cfg type"

This reverts commit 9503491f7076ea923b6ee83364ccdfe2cd4f46cf.